// ============================================================
// CONTRIBUTIONS DATA  —  divakar-amd (Divakar Verma)
// ============================================================
// Five sections:
//   PULL_REQUESTS  — individual GitHub PRs (add new ones here)
//   ISSUES         — GitHub issues filed
//   REVIEWS        — formal reviews (approve/request changes) on others' PRs
//   COMMENTS       — notable standalone comments on PRs/issues
//   INTERNAL_WORK  — internal AMD work, client deliverables,
//                    analysis, knowledge sharing (no GitHub URL)
// ============================================================

const PROFILE = {
  name: "Divakar Verma",
  title: "GPU Software Engineer",
  company: "AMD",
  github: "divakar-amd",
  githubUrl: "https://github.com/divakar-amd",
  focus: "vLLM / ROCm Inference Optimization",
  summary: "Core upstream vLLM contributor for AMD — built ROCm's MoE tuning infrastructure for vLLM; added end-to-end w4a8 Quark quantization stack powering gpt-oss-120b serving today; improved performance; resolved critical regressions; drove ROCm vLLM CI health."
};

// ── Repositories ─────────────────────────────────────────
const REPO = {
  VLLM_UPSTREAM:  "vllm-project/vllm",
  VLLM_ROCM:      "ROCm/vllm",
  AITER:          "ROCm/aiter",
  TRITON_ROCM:    "ROCm/triton",
  XGRAMMAR:       "mlc-ai/xgrammar",
  PYTORCH_ROCM:   "ROCm/pytorch",
};

// ── Categories ─────────────────────────────────────────
const CAT = {
  KERNEL:    "Kernel Development",
  MOE:       "MoE Optimization",
  CLIENT:    "Client Deliverables",
  INFRA:     "Infrastructure & CI",
  BUGFIX:    "Bug Fixes",
  ANALYSIS:  "Analysis & Benchmarking",
  MODEL:     "Model Support",
  KNOWLEDGE: "Knowledge Sharing",
  QUANT:     "Quantization",
  MISC:      "Miscellaneous",
};

// ── PR States ─────────────────────────────────────────
const STATE = {
  MERGED:  "merged",
  OPEN:    "open",
  CLOSED:  "closed",   // closed without merge
  DRAFT:   "draft",
};

// ── Top Projects Delivered ─────────────────────────────────
// The headline section: major initiatives rather than individual PRs.
// Each project pulls together PRs (PULL_REQUESTS), internal work
// (INTERNAL_WORK), and issues (ISSUES) into one story. `items` is
// ordered by importance — the first 3 render open, the rest behind
// a "+N more" toggle. Reference items by their `id` field.
const PROJECTS = [
  {
    id: "proj-moe-tuning",
    title: "ROCm MoE Auto-Tuning Infrastructure — Built From Scratch",
    summary: "Designed and built ROCm's MoE kernel auto-tuning system from the ground up — the foundation all later AMD MoE kernel work (FP8 block quant, per-model configs) builds on.",
    impact: "40% (TP1) / 25% (TP2) / 18% (TP4) / 12% (TP8) throughput gains on MI308; formed the standard tuning path for every new MoE model on ROCm",
    tags: ["MoE", "ROCm", "Triton", "Auto-Tuning"],
    items: [
      { type: "pr", id: "vllm-12049" },
      { type: "pr", id: "vllm-14068" },
      { type: "pr", id: "vllm-4951" },
      { type: "pr", id: "vllm-4927" },
      { type: "pr", id: "rocmvllm-13" },
      { type: "pr", id: "rocmvllm-14" },
    ],
  },
  {
    id: "proj-w4a8",
    title: "W4A8 Quark Quantization Stack for gpt-oss-120b",
    summary: "Delivered the end-to-end w4a8 (mxfp4×fp8) quantization pipeline on ROCm — from LinearLayer support through fp8×fp8 attention — enabling gpt-oss-120b serving at low precision.",
    impact: "120B model serving at w4a8 precision validated and delivered end-to-end",
    tags: ["w4a8", "FP8", "Quark", "Quantization", "gpt-oss-120b"],
    items: [
      { type: "pr", id: "vllm-35316" },
      { type: "pr", id: "vllm-36927" },
      { type: "pr", id: "vllm-38296" },
    ],
  },
  {
    id: "proj-ci-health",
    title: "vLLM Upstream CI Health for AMD / ROCm",
    summary: "Drove ROCm CI reliability across the vLLM upstream test suite and the AITER pipeline — restoring failing ROCm test groups to green and improving overall CI stability.",
    impact: "26+ merged CI/infra PRs upstream; AITER CI build time: 6 hrs → 12 min (30× speedup)",
    tags: ["CI", "ROCm", "Infrastructure", "GitHub Actions"],
    items: [
      { type: "pr", id: "vllm-46658" },
      { type: "pr", id: "aiter-1124" },
      { type: "pr", id: "vllm-11813" },
      { type: "pr", id: "vllm-8971" },
      { type: "pr", id: "vllm-32787" },
      { type: "pr", id: "vllm-42104" },
      { type: "pr", id: "vllm-45869" },
    ],
  },
  {
    id: "proj-bmm-deepseek",
    title: "Triton FP8 BMM Kernel Integration for DeepSeek MLA",
    summary: "Integrated AITER Triton FP8 batch matmul kernel for DeepSeek's multi-head latent attention (MLA) on ROCm, replacing torch.bmm and eliminating a first-request compile stall — then carried it through to production client deployments.",
    impact: "Improved DeepSeek-R1 serving throughput on ROCm; unblocked key clients' production DeepSeek deployments on AMD",
    tags: ["Triton", "FP8", "BMM", "MLA", "DeepSeek", "ROCm"],
    items: [
      { type: "pr", id: "vllm-23264" },
    ],
  },
  {
    id: "proj-regression-fixes",
    title: "Critical Performance improvements and Regression Fixes",
    summary: "Root-caused and fixed high-severity, production-blocking regressions on ROCm including a Mistral throughput regression and a torch.compile activation-fusion correctness bug.",
    impact: "Resolved a 10–90% Mistral throughput regression and a torch.compile+GELU bug that produced garbage output on Gemma3/StarCoder2",
    tags: ["Bugfix", "ROCm", "Performance", "Correctness"],
    items: [
      { type: "pr", id: "vllm-4927" },
      { type: "pr", id: "vllm-16426" },
      { type: "pr", id: "vllm-29244" },
    ],
  },
  {
    id: "proj-client-sla",
    title: "Client SLA Deliverables — Priority Production Serving",
    summary: "Served as the AMD-side performance and correctness contributor across major inference clients, meeting hard throughput and latency SLAs on production timelines.",
    impact: "SLAs met for Alibaba (1.3× Mixtral throughput), ByteDance (23ms decode latency)",
    tags: ["Client Deliverables", "SLA", "Serving"],
    items: [
    ],
  },
  {
    id: "proj-misc",
    title: "Miscellaneous — Cross-Cutting Investigations & Knowledge Sharing",
    summary: "Deep-dive investigations, root-cause analysis, and internal documentation that don't map to a single deliverable but informed production decisions and team onboarding.",
    impact: "Root-caused a ROCm PyTorch memory bug (hipblasLT pool) and a HipGraph capture-size mismatch (fixed in ROCm-7); authored reference docs used across the team",
    tags: ["Analysis", "Knowledge Sharing", "Investigation"],
    items: [
      { type: "issue", id: "issue-pytorch-2286" },
      { type: "issue", id: "issue-vllm-19579" },
      { type: "pr", id: "vllm-18445" },
    ],
  },
];


// ============================================================
// PULL REQUESTS
// ============================================================
const PULL_REQUESTS = [
  // ── 🆕 New PRs auto-added by fetch_contributions.py — review & enrich ──
  {
    id: "vllm-46758",
    repo: REPO.VLLM_UPSTREAM,
    number: 46758,
    url: "https://github.com/vllm-project/vllm/pull/46758",
    title: "[ROCm][CI TG] refactor and fix deepep_moe test group",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-25",
    mergedDate: "2026-06-27",
    tags: [],
    description: "",
  },
  {
    id: "vllm-46729",
    repo: REPO.VLLM_UPSTREAM,
    number: 46729,
    url: "https://github.com/vllm-project/vllm/pull/46729",
    title: "[ROCm][CI] rm duplicate Distributed Torchrun ci test",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-25",
    mergedDate: "2026-06-25",
    tags: [],
    description: "",
  },
  {
    id: "vllm-46658",
    repo: REPO.VLLM_UPSTREAM,
    number: 46658,
    url: "https://github.com/vllm-project/vllm/pull/46658",
    title: "[ROCm][CI] Relax fused layernorm quant test tolerances for one-ULP outliers",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-24",
    mergedDate: "2026-06-27",
    tags: [],
    description: "",
  },
  {
    id: "vllm-46410",
    repo: REPO.VLLM_UPSTREAM,
    number: 46410,
    url: "https://github.com/vllm-project/vllm/pull/46410",
    title: "[ROCm][CI] fix fp8 range in vit_fp8_quant",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-22",
    mergedDate: "2026-06-23",
    tags: [],
    description: "",
  },
  {
    id: "vllm-46409",
    repo: REPO.VLLM_UPSTREAM,
    number: 46409,
    url: "https://github.com/vllm-project/vllm/pull/46409",
    title: "[ROCm][CI]Fix test_concat_and_cache_mla_rope_fused on ROCm",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-22",
    mergedDate: "2026-06-27",
    tags: [],
    description: "",
  },
  {
    id: "vllm-45970",
    repo: REPO.VLLM_UPSTREAM,
    number: 45970,
    url: "https://github.com/vllm-project/vllm/pull/45970",
    title: "[ROCm][CI] move lora%N test to mi300 and gate",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-17",
    mergedDate: "2026-06-18",
    tags: [],
    description: "",
  },
  {
    id: "vllm-45869",
    repo: REPO.VLLM_UPSTREAM,
    number: 45869,
    url: "https://github.com/vllm-project/vllm/pull/45869",
    title: "[ROCm][CI] pass merge-base to container for python-only wheel metadata",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-16",
    mergedDate: "2026-06-23",
    tags: [],
    description: "",
  },
  {
    id: "vllm-45858",
    repo: REPO.VLLM_UPSTREAM,
    number: 45858,
    url: "https://github.com/vllm-project/vllm/pull/45858",
    title: "[ROCm][CI] fix multimodel run cmds",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-16",
    mergedDate: "2026-06-16",
    tags: [],
    description: "",
  },
  {
    id: "vllm-45302",
    repo: REPO.VLLM_UPSTREAM,
    number: 45302,
    url: "https://github.com/vllm-project/vllm/pull/45302",
    title: "[ROCm][CI] fix fp8 support for test_deepep_moe",
    state: STATE.MERGED,
    categories: [CAT.INFRA, CAT.BUGFIX],
    date: "2026-06-11",
    mergedDate: "2026-06-12",
    tags: [],
    description: "",
  },
  {
    id: "vllm-45072",
    repo: REPO.VLLM_UPSTREAM,
    number: 45072,
    url: "https://github.com/vllm-project/vllm/pull/45072",
    title: "[bugfix] skip conch kernel for g_idx reordering",
    state: STATE.MERGED,
    category: CAT.BUGFIX, // TODO: set real category/tags/description
    date: "2026-06-09",
    mergedDate: "2026-06-10",
    tags: [],
    description: "",
  },
  {
    id: "vllm-44436",
    repo: REPO.VLLM_UPSTREAM,
    number: 44436,
    url: "https://github.com/vllm-project/vllm/pull/44436",
    title: "[ROCm][CI] Add test for Aiter unified attn kernel",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-06-03",
    mergedDate: "2026-06-04",
    tags: [],
    description: "",
  },
  {
    id: "vllm-43236",
    repo: REPO.VLLM_UPSTREAM,
    number: 43236,
    url: "https://github.com/vllm-project/vllm/pull/43236",
    title: "[ROCm][CI] add warmup to mem_util test before measurement",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-05-20",
    mergedDate: "2026-05-22",
    tags: [],
    description: "",
  },
  {
    id: "vllm-42104",
    repo: REPO.VLLM_UPSTREAM,
    number: 42104,
    url: "https://github.com/vllm-project/vllm/pull/42104",
    title: "[CI] set max transformers version for skywork model",
    state: STATE.MERGED,
    category: CAT.INFRA, // TODO: set real category/tags/description
    date: "2026-05-08",
    mergedDate: "2026-05-13",
    tags: [],
    description: "",
  },
  {
    id: "vllm-29809",
    repo: REPO.VLLM_UPSTREAM,
    number: 29809,
    url: "https://github.com/vllm-project/vllm/pull/29809",
    title: "[llama4_eagle] add lm_head attribute to model class",
    state: STATE.DRAFT,
    category: CAT.MODEL, // TODO: set real category/tags/description
    date: "2025-12-01",
    tags: [],
    description: "",
  },
  {
    id: "vllm-29254",
    repo: REPO.VLLM_UPSTREAM,
    number: 29254,
    url: "https://github.com/vllm-project/vllm/pull/29254",
    title: "[CI][ROCm] (wip) Fix test_async_scheduing",
    state: STATE.DRAFT,
    category: "Uncategorized", // TODO: set real category/tags/description
    date: "2025-11-23",
    tags: [],
    description: "",
  },
  {
    id: "vllm-29120",
    repo: REPO.VLLM_UPSTREAM,
    number: 29120,
    url: "https://github.com/vllm-project/vllm/pull/29120",
    title: "[CI][ROCm] Fix multiprocessing launch for the test on ROCm",
    state: STATE.CLOSED,
    category: "Uncategorized", // TODO: set real category/tags/description
    date: "2025-11-20",
    tags: [],
    description: "",
  },
  {
    id: "vllm-29113",
    repo: REPO.VLLM_UPSTREAM,
    number: 29113,
    url: "https://github.com/vllm-project/vllm/pull/29113",
    title: "[CI][ROCm][v1/e2e][1/n] Fix multiprocessing for AMD gpu",
    state: STATE.CLOSED,
    category: "Uncategorized", // TODO: set real category/tags/description
    date: "2025-11-20",
    tags: [],
    description: "",
  },
  {
    id: "vllm-22759",
    repo: REPO.VLLM_UPSTREAM,
    number: 22759,
    url: "https://github.com/vllm-project/vllm/pull/22759",
    title: "[ROCm][Aiter] Add triton fp8 bmm kernel for mla",
    state: STATE.CLOSED,
    category: "Uncategorized", // TODO: set real category/tags/description
    date: "2025-08-12",
    tags: [],
    description: "",
  },
  {
    id: "vllm-12838",
    repo: REPO.VLLM_UPSTREAM,
    number: 12838,
    url: "https://github.com/vllm-project/vllm/pull/12838",
    title: "[rocm][moe] pruning fix for moe tuning",
    state: STATE.CLOSED,
    category: "Uncategorized", // TODO: set real category/tags/description
    date: "2025-02-06",
    tags: [],
    description: "",
  },
  {
    id: "vllm-9820",
    repo: REPO.VLLM_UPSTREAM,
    number: 9820,
    url: "https://github.com/vllm-project/vllm/pull/9820",
    title: "[Kernel][ROCm][AMD] fp8 moe configs for MI300X. Mixtral-8x(7B,22B) TP=1,2,4,8",
    state: STATE.CLOSED,
    category: "Uncategorized", // TODO: set real category/tags/description
    date: "2024-10-29",
    tags: [],
    description: "",
  },

  // ── vllm-project/vllm ────────────────────────────────

  {
    mergedDate: "2026-05-06",
    id: "vllm-38296",
    repo: REPO.VLLM_UPSTREAM,
    number: 38296,
    url: "https://github.com/vllm-project/vllm/pull/38296",
    title: "[ROCm] aiter_unified_attn fp8 q scale refactor",
    state: STATE.MERGED,
    category: CAT.QUANT,
    date: "2026-03-27",
    tags: ["FP8", "Attention", "ROCm", "Refactor"],
    description: "Refactoring FP8 q scale handling in aiter unified attention for cleaner abstraction.",
  },
  {
    id: "vllm-37606",
    repo: REPO.VLLM_UPSTREAM,
    number: 37606,
    url: "https://github.com/vllm-project/vllm/pull/37606",
    title: "[ROCm][Bugfix] fix cache block size mismatch for aiter unified attention",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2026-03-19",
    mergedDate: "2026-03-20",
    tags: ["KV-Cache", "Attention", "ROCm", "Bugfix"],
    description: "Fixed cache block size mismatch that caused failures in aiter unified attention path.",
  },
  {
    id: "vllm-36927",
    repo: REPO.VLLM_UPSTREAM,
    number: 36927,
    url: "https://github.com/vllm-project/vllm/pull/36927",
    title: "[ROCm][Quantization] add fp8xfp8 attn support for rocm_aiter_unified_attn",
    state: STATE.MERGED,
    category: CAT.QUANT,
    date: "2026-03-12",
    mergedDate: "2026-03-18",
    tags: ["FP8", "Attention", "Quantization", "ROCm"],
    description: "Added fp8×fp8 attention computation support in the ROCm aiter unified attention kernel.",
    impact: "Completed the full fp8 (weights+activations+attention) quantized serving pipeline for gpt-oss-120b on ROCm, following #35316",
  },
  {
    id: "vllm-35316",
    repo: REPO.VLLM_UPSTREAM,
    number: 35316,
    url: "https://github.com/vllm-project/vllm/pull/35316",
    title: "[ROCm][Quantization] add quark w4a8 mxfp4_fp8 for LinearLayer",
    state: STATE.MERGED,
    category: CAT.QUANT,
    date: "2026-02-25",
    mergedDate: "2026-03-13",
    tags: ["w4a8", "FP8", "Quark", "Quantization", "LinearLayer"],
    description: "Added Quark w4a8 (mxfp4×fp8) quantization support for LinearLayer to enable gpt-oss-120b serving.",
    impact: "Enabled w4a8 quantized gpt-oss-120b serving on ROCm — foundational quant path later extended to fp8 attention (PR #36927)",
  },
  {
    id: "vllm-34977",
    repo: REPO.VLLM_UPSTREAM,
    number: 34977,
    url: "https://github.com/vllm-project/vllm/pull/34977",
    title: "[Mamba][APC] Add test case to compare apc outputs ",
    state: STATE.MERGED,
    category: CAT.MODEL,
    date: "2026-02-20",
    mergedDate: "2026-03-26",
    tags: ["Mamba", "Testing", "APC"],
    description: "Added test case for Mamba APC (Automatic Prefix Caching) output comparison.",
  },
  {
    id: "vllm-32787",
    repo: REPO.VLLM_UPSTREAM,
    number: 32787,
    url: "https://github.com/vllm-project/vllm/pull/32787",
    title: "[ROCm][CI] fix get_valid_backends",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2026-01-21",
    mergedDate: "2026-01-22",
    tags: ["CI", "ROCm", "Bugfix"],
    description: "Fixed get_valid_backends function in ROCm CI to correctly enumerate available attention backends.",
  },
  {
    id: "vllm-32783",
    repo: REPO.VLLM_UPSTREAM,
    number: 32783,
    url: "https://github.com/vllm-project/vllm/pull/32783",
    title: "[ROCm] fix import for on_gfx9",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2026-01-21",
    mergedDate: "2026-01-21",
    tags: ["ROCm", "GFX9", "Import", "Bugfix"],
    description: "Fixed import path for on_gfx9 hardware detection utility on ROCm.",
  },
  {
    id: "vllm-32727",
    repo: REPO.VLLM_UPSTREAM,
    number: 32727,
    url: "https://github.com/vllm-project/vllm/pull/32727",
    title: "[bugfix] Aria model",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2026-01-20",
    mergedDate: "2026-01-21",
    tags: ["Aria", "Model", "Bugfix"],
    description: "Fixed a bug in the Aria model implementation in vLLM.",
  },
  {
    id: "vllm-32040",
    repo: REPO.VLLM_UPSTREAM,
    number: 32040,
    url: "https://github.com/vllm-project/vllm/pull/32040",
    title: "[ROCm][CI] Handle pytest status code 5 when a shard isn't allocated any tests ",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2026-01-09",
    mergedDate: "2026-01-12",
    tags: ["CI", "ROCm", "pytest"],
    description: "Fixed CI failure when pytest exits with code 5 (no tests collected) for unallocated shards.",
  },
  {
    id: "vllm-31993",
    repo: REPO.VLLM_UPSTREAM,
    number: 31993,
    url: "https://github.com/vllm-project/vllm/pull/31993",
    title: "[ROCm][CI] Fix test_token_classification.py::test_bert_models",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2026-01-08",
    mergedDate: "2026-01-09",
    tags: ["CI", "ROCm", "BERT", "Testing"],
    description: "Fixed BERT token classification test failure in the ROCm CI pipeline.",
  },
  {
    id: "vllm-31192",
    repo: REPO.VLLM_UPSTREAM,
    number: 31192,
    url: "https://github.com/vllm-project/vllm/pull/31192",
    title: "[AMD][CI] fix v1/engine test_preprocess_error_handling",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-12-22",
    mergedDate: "2025-12-23",
    tags: ["CI", "AMD", "vLLM-V1", "Testing"],
    description: "Fixed preprocessing error handling test for the vLLM V1 engine on AMD CI.",
  },
  {
    id: "vllm-30911",
    repo: REPO.VLLM_UPSTREAM,
    number: 30911,
    url: "https://github.com/vllm-project/vllm/pull/30911",
    title: "[AMD][CI] fix lm eval ci arg",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-12-17",
    mergedDate: "2025-12-18",
    tags: ["CI", "AMD", "lm-eval"],
    description: "Fixed incorrect argument passed to lm-eval in the AMD CI pipeline.",
  },
  {
    id: "vllm-29926",
    repo: REPO.VLLM_UPSTREAM,
    number: 29926,
    url: "https://github.com/vllm-project/vllm/pull/29926",
    title: "[Bugfix][llama4_eagle] Fix missing 'lm_head' attribute",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2025-12-03",
    mergedDate: "2025-12-05",
    tags: ["Llama4", "Eagle", "Bugfix", "Speculative Decoding"],
    description: "Fixed missing lm_head attribute in llama4_eagle model class that caused speculative decoding failures.",
  },
  {
    id: "vllm-29827",
    repo: REPO.VLLM_UPSTREAM,
    number: 29827,
    url: "https://github.com/vllm-project/vllm/pull/29827",
    title: "[CI][AMD] spec_decode:eagle skip FLASH_ATTN for deepseek on ROCm",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-12-02",
    mergedDate: "2025-12-02",
    tags: ["CI", "AMD", "Speculative Decoding", "Deepseek", "Flash Attention"],
    description: "Skipped unsupported Flash Attention path for Deepseek speculative decoding tests on ROCm.",
  },
  {
    id: "vllm-29439",
    repo: REPO.VLLM_UPSTREAM,
    number: 29439,
    url: "https://github.com/vllm-project/vllm/pull/29439",
    title: "[Bugfix] Fix grouped_topk pytorch impl when num_experts can't be grouped properly",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2025-11-25",
    mergedDate: "2025-12-11",
    tags: ["MoE", "TopK", "Bugfix", "Expert Routing"],
    description: "Fixed incorrect grouped top-k implementation in PyTorch fallback path for MoE expert grouping.",
  },
  {
    id: "vllm-29344",
    repo: REPO.VLLM_UPSTREAM,
    number: 29344,
    url: "https://github.com/vllm-project/vllm/pull/29344",
    title: "[CI][ROCm] Install arctic-inference on ROCm tests",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-11-24",
    mergedDate: "2025-11-25",
    tags: ["CI", "ROCm", "arctic-inference"],
    description: "Added arctic-inference installation to ROCm CI test environment.",
  },
  {
    id: "vllm-29244",
    repo: REPO.VLLM_UPSTREAM,
    number: 29244,
    url: "https://github.com/vllm-project/vllm/pull/29244",
    title: "[ROCm] Fallback pytorch GELU with tanh approximation to GELU()",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2025-11-22",
    mergedDate: "2025-12-02",
    tags: ["ROCm", "GELU", "Activation", "Bugfix"],
    description: "Added PyTorch fallback for GELU with tanh approximation on ROCm where the fused kernel is unsupported.",
    impact: "Fixed a torch.compile + tanh-approx GELU bug on ROCm that produced garbage output for Gemma3 and StarCoder2",
  },
  {
    id: "vllm-29243",
    repo: REPO.VLLM_UPSTREAM,
    number: 29243,
    url: "https://github.com/vllm-project/vllm/pull/29243",
    title: "[CI][ROCm] Fix test_correctness_sliding_window",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-11-22",
    mergedDate: "2025-12-02",
    tags: ["CI", "ROCm", "Sliding Window", "Testing"],
    description: "Fixed sliding window attention correctness test failures in the ROCm CI pipeline.",
  },
  {
    id: "vllm-29123",
    repo: REPO.VLLM_UPSTREAM,
    number: 29123,
    url: "https://github.com/vllm-project/vllm/pull/29123",
    title: "[CI][ROCm][tests/v1/e2e] Fix multiprocessing launch for the test",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-11-20",
    mergedDate: "2025-12-02",
    tags: ["CI", "ROCm", "vLLM-V1", "Multiprocessing"],
    description: "Fixed multiprocessing launch failure in V1 end-to-end tests on AMD GPUs.",
  },
  {
    id: "vllm-23264",
    repo: REPO.VLLM_UPSTREAM,
    number: 23264,
    url: "https://github.com/vllm-project/vllm/pull/23264",
    title: "[ROCm][Aiter] Add triton fp8 bmm kernel for mla",
    state: STATE.MERGED,
    category: CAT.KERNEL,
    date: "2025-08-20",
    mergedDate: "2025-08-28",
    tags: ["Triton", "FP8", "BMM", "MLA", "Deepseek", "ROCm"],
    description: "Added Triton FP8 batch matrix multiplication kernel for Deepseek MLA (multi-head latent attention) with pre-compilation warmup optimization.",
    impact: "Improved DeepSeek-R1 serving throughput on ROCm by replacing torch.bmm with a tuned FP8 Triton kernel; pre-compilation step eliminated a first-request kernel-compile stall",
  },
  {
    id: "vllm-18445",
    repo: REPO.VLLM_UPSTREAM,
    number: 18445,
    url: "https://github.com/vllm-project/vllm/pull/18445",
    title: "[V1] fix torch profiling for V1 offline scenarios",
    state: STATE.MERGED,
    category: CAT.MISC,
    date: "2025-05-21",
    mergedDate: "2025-05-28",
    tags: ["vLLM-V1", "Profiling", "torch.profiler", "Bugfix"],
    description: "Fixed torch profiler trace collection in vLLM V1 offline inference, restoring profiling capability for all V1 users.",
    impact: "Restored torch profiler traces for V1 offline benchmarking (previously empty since the GPU worker runs in a separate process) and added automatic kernel-summary dumps",
  },
  {
    id: "vllm-16847",
    repo: REPO.VLLM_UPSTREAM,
    number: 16847,
    url: "https://github.com/vllm-project/vllm/pull/16847",
    title: "[rocm][MI300] llama4 maverick fp8 moe config tp8",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-04-18",
    mergedDate: "2025-04-19",
    tags: ["Llama4", "FP8", "MoE", "MI300", "Config", "TP8"],
    description: "Added tuned FP8 MoE configs for Llama4 Maverick at TP8 on MI300 hardware.",
  },
  {
    id: "vllm-16426",
    repo: REPO.VLLM_UPSTREAM,
    number: 16426,
    url: "https://github.com/vllm-project/vllm/pull/16426",
    title: "[rocm][V0] fix selection logic for custom PA in V0",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2025-04-10",
    mergedDate: "2025-04-17",
    tags: ["ROCm", "Paged Attention", "V0", "Bugfix", "Performance"],
    description: "Fixed selection logic for custom paged attention in vLLM V0 that caused 10–90% Mistral performance regression.",
    impact: "Resolved 10–90% performance regression for Mistral models on ROCm",
  },
  {
    id: "vllm-14068",
    repo: REPO.VLLM_UPSTREAM,
    number: 14068,
    url: "https://github.com/vllm-project/vllm/pull/14068",
    title: "[core] moe fp8 block quant tuning support",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-03-01",
    mergedDate: "2025-03-04",
    tags: ["MoE", "FP8", "Quantization", "Tuning"],
    description: "Added FP8 block quantization tuning support for MoE kernels in the core vLLM codebase.",
    impact: "Upgraded MoE tuner to account for FP8 block-quantization weight scales — required for generating correct/optimal kernel configs for DeepSeek-V3",
  },
  {
    id: "vllm-13577",
    repo: REPO.VLLM_UPSTREAM,
    number: 13577,
    url: "https://github.com/vllm-project/vllm/pull/13577",
    title: "[ROCm][MoE] mi300 mixtral8x7B perf for specific BS",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-02-20",
    mergedDate: "2025-02-20",
    tags: ["MoE", "MI300", "Mixtral", "Tuning", "Performance"],
    description: "Added MI300-specific Mixtral-8x7B MoE tuned configs for targeted batch sizes.",
  },
  {
    id: "vllm-13503",
    repo: REPO.VLLM_UPSTREAM,
    number: 13503,
    url: "https://github.com/vllm-project/vllm/pull/13503",
    title: "[ROCm][MoE configs] mi325 mixtral & mi300 qwen_moe ",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-02-18",
    mergedDate: "2025-02-19",
    tags: ["MoE", "MI325", "MI300", "Mixtral", "Qwen", "Config"],
    description: "Added MoE tuned configs for Mixtral on MI325 and Qwen-MoE on MI300.",
  },
  {
    id: "vllm-13438",
    repo: REPO.VLLM_UPSTREAM,
    number: 13438,
    url: "https://github.com/vllm-project/vllm/pull/13438",
    title: "[ROCm] fix get_device_name for rocm",
    state: STATE.MERGED,
    category: CAT.MISC,
    date: "2025-02-18",
    mergedDate: "2025-02-18",
    tags: ["ROCm", "Device", "Bugfix"],
    description: "Fixed device name detection for ROCm GPUs to return correct hardware identifiers.",
  },
  {
    id: "vllm-12558",
    repo: REPO.VLLM_UPSTREAM,
    number: 12558,
    url: "https://github.com/vllm-project/vllm/pull/12558",
    title: "[Misc][MoE] add Deepseek-V3 moe tuning support",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-01-29",
    mergedDate: "2025-01-30",
    tags: ["Deepseek", "MoE", "Tuning", "V3"],
    description: "Added Deepseek-V3 MoE architecture support to the MoE tuning pipeline.",
  },
  {
    id: "vllm-12408",
    repo: REPO.VLLM_UPSTREAM,
    number: 12408,
    url: "https://github.com/vllm-project/vllm/pull/12408",
    title: "[ROCm][MoE] MI300 tuned configs Mixtral-8x(7B,22B) | fp16, fp8 ",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-01-24",
    mergedDate: "2025-01-25",
    tags: ["MoE", "MI300", "Mixtral", "Config", "Tuning"],
    description: "Added MI300 tuned MoE configs for Mixtral-8x7B and Mixtral-8x22B.",
  },
  {
    id: "vllm-12273",
    repo: REPO.VLLM_UPSTREAM,
    number: 12273,
    url: "https://github.com/vllm-project/vllm/pull/12273",
    title: "[bugfix] moe tuning. rm is_navi()",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2025-01-21",
    mergedDate: "2025-01-21",
    tags: ["MoE", "Tuning", "Navi", "Bugfix"],
    description: "Removed incorrect is_navi() gate from MoE tuning path that was blocking non-Navi hardware.",
  },
  {
    id: "vllm-12049",
    repo: REPO.VLLM_UPSTREAM,
    number: 12049,
    url: "https://github.com/vllm-project/vllm/pull/12049",
    title: "[ROCm][MoE] moe tuning support for rocm",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-01-14",
    mergedDate: "2025-01-17",
    tags: ["MoE", "ROCm", "Tuning", "Infrastructure"],
    description: "Added full MoE kernel tuning infrastructure support for ROCm, enabling auto-tuning on AMD hardware.",
    impact: "Established the ROCm MoE auto-tuning infrastructure (FP16 + FP8, config pruning) — the foundation all later AMD MoE kernel tuning (incl. #14068) builds on",
  },
  {
    id: "vllm-11813",
    repo: REPO.VLLM_UPSTREAM,
    number: 11813,
    url: "https://github.com/vllm-project/vllm/pull/11813",
    title: "[Misc] sort torch profiler table by kernel timing",
    state: STATE.MERGED,
    category: CAT.MISC,
    date: "2025-01-07",
    mergedDate: "2025-01-08",
    tags: ["Profiling", "torch.profiler", "UX"],
    description: "Improved torch profiler output by sorting the kernel timing table by duration for easier analysis.",
  },
  {
    id: "vllm-8971",
    repo: REPO.VLLM_UPSTREAM,
    number: 8971,
    url: "https://github.com/vllm-project/vllm/pull/8971",
    title: "[Misc] log when using default MoE config",
    state: STATE.MERGED,
    category: CAT.MISC,
    date: "2024-09-30",
    mergedDate: "2024-10-03",
    tags: ["MoE", "Logging", "UX"],
    description: "Added logging to indicate when the default (untuned) MoE config is being used, aiding debugging.",
  },
  {
    id: "vllm-8969",
    repo: REPO.VLLM_UPSTREAM,
    number: 8969,
    url: "https://github.com/vllm-project/vllm/pull/8969",
    title: "[Misc] add process_weights_after_loading for DummyLoader",
    state: STATE.MERGED,
    category: CAT.MODEL,
    date: "2024-09-30",
    mergedDate: "2024-10-01",
    tags: ["DummyLoader", "Weight Loading", "Testing"],
    description: "Extended DummyLoader to support process_weights_after_loading, enabling FP8 and MoE-padded model profiling.",
  },
  {
    id: "vllm-8518",
    repo: REPO.VLLM_UPSTREAM,
    number: 8518,
    url: "https://github.com/vllm-project/vllm/pull/8518",
    title: "[dbrx] refactor dbrx experts to extend FusedMoe class",
    state: STATE.MERGED,
    category: CAT.MODEL,
    date: "2024-09-16",
    mergedDate: "2024-09-21",
    tags: ["DBRX", "MoE", "Refactor", "Databricks"],
    description: "Refactored DBRX expert layer to inherit from FusedMoe class, enabling MoE optimizations for Databricks' model.",
    impact: "Unlocked FusedMoe-class optimizations (fused kernels, quantization support) for DBRX — key model for Databricks client engagement",
  },
  {
    id: "vllm-5932",
    repo: REPO.VLLM_UPSTREAM,
    number: 5932,
    url: "https://github.com/vllm-project/vllm/pull/5932",
    title: "[Kernel][ROCm][AMD] fused_moe Triton configs v2 for mi300X",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-06-27",
    mergedDate: "2024-06-27",
    tags: ["MoE", "Triton", "MI300X", "Config", "Kernel"],
    description: "Second generation tuned Triton fused_moe kernel configs for MI300X GPU.",
  },
  {
    id: "vllm-4951",
    repo: REPO.VLLM_UPSTREAM,
    number: 4951,
    url: "https://github.com/vllm-project/vllm/pull/4951",
    title: "[Kernel][ROCm][AMD] Add fused_moe Triton configs for MI300X",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-05-21",
    mergedDate: "2024-05-28",
    tags: ["MoE", "Triton", "MI300X", "Config", "Kernel"],
    description: "First set of tuned Triton fused_moe kernel configs for MI300X — initial upstream MoE tuning contribution.",
    impact: "First upstream MoE kernel tuning contribution for MI300X — established the config format/pattern later scaled up by the ROCm MoE tuning infrastructure (#12049)",
  },
  {
    id: "vllm-4927",
    repo: REPO.VLLM_UPSTREAM,
    number: 4927,
    url: "https://github.com/vllm-project/vllm/pull/4927",
    title: "[Kernel][ROCm][AMD] enable fused topk_softmax kernel for moe layer",
    state: STATE.MERGED,
    category: CAT.KERNEL,
    date: "2024-05-20",
    mergedDate: "2024-06-02",
    tags: ["Triton", "TopK", "Softmax", "MoE", "Kernel", "ROCm"],
    description: "Enabled fused top-k + softmax Triton kernel for the MoE routing layer, reducing kernel launch overhead.",
    impact: "5%+ throughput improvement on MoE models",
  },

  // ── ROCm/vllm ────────────────────────────────────────

  {
    id: "rocmvllm-507",
    repo: REPO.VLLM_ROCM,
    number: 507,
    url: "https://github.com/ROCm/vllm/pull/507",
    title: "Update moe_tune_script.sh",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-04-07",
    mergedDate: "2025-04-08",
    tags: ["MoE", "Tuning", "Script"],
    description: "Updated the MoE tuning shell script for improved usability and correctness.",
  },
  {
    id: "rocmvllm-483",
    repo: REPO.VLLM_ROCM,
    number: 483,
    url: "https://github.com/ROCm/vllm/pull/483",
    title: "use unified fp8 notation in FA",
    state: STATE.MERGED,
    category: CAT.QUANT,
    date: "2025-03-14",
    mergedDate: "2025-03-14",
    tags: ["FP8", "Flash Attention", "Refactor"],
    description: "Unified FP8 notation in Flash Attention for consistency with upstream.",
  },
  {
    id: "rocmvllm-437",
    repo: REPO.VLLM_ROCM,
    number: 437,
    url: "https://github.com/ROCm/vllm/pull/437",
    title: "resolve configs diff for mixtral8x7B",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2025-02-19",
    mergedDate: "2025-02-20",
    tags: ["MoE", "Mixtral", "Config", "Sync"],
    description: "Resolved config drift for Mixtral-8x7B between ROCm fork and upstream.",
  },
  {
    id: "rocmvllm-359",
    repo: REPO.VLLM_ROCM,
    number: 359,
    url: "https://github.com/ROCm/vllm/pull/359",
    title: "fix rocm get_device name",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2025-01-14",
    mergedDate: "2025-02-07",
    tags: ["ROCm", "Device", "Bugfix"],
    description: "Fixed ROCm device name detection in the AMD fork.",
  },
  {
    id: "rocmvllm-305",
    repo: REPO.VLLM_ROCM,
    number: 305,
    url: "https://github.com/ROCm/vllm/pull/305",
    title: "rm old moe tune file. Add bash script for tuning reference",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-12-04",
    mergedDate: "2024-12-04",
    tags: ["MoE", "Tuning", "Script", "Cleanup"],
    description: "Removed stale MoE tuning file and added a clean bash script as a reference tuning tool.",
  },
  {
    id: "rocmvllm-304",
    repo: REPO.VLLM_ROCM,
    number: 304,
    url: "https://github.com/ROCm/vllm/pull/304",
    title: "re-tune fp8 mixtral8x22B",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-12-04",
    mergedDate: "2024-12-04",
    tags: ["MoE", "FP8", "Mixtral", "MI300"],
    description: "Re-tuned FP8 MoE configs for Mixtral-8x22B on MI300 hardware.",
  },
  {
    id: "rocmvllm-277",
    repo: REPO.VLLM_ROCM,
    number: 277,
    url: "https://github.com/ROCm/vllm/pull/277",
    title: "mixtral8x22B moe configs mi300 TP=1,2,4,8",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-11-14",
    mergedDate: "2024-11-14",
    tags: ["MoE", "Mixtral", "MI300", "Config", "TP"],
    description: "Added MI300 MoE tuned configs for Mixtral-8x22B across all tensor parallel degrees (TP=1,2,4,8).",
  },
  {
    id: "rocmvllm-251",
    repo: REPO.VLLM_ROCM,
    number: 251,
    url: "https://github.com/ROCm/vllm/pull/251",
    title: "rocm support for moe tuning script",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-10-30",
    mergedDate: "2024-11-13",
    tags: ["MoE", "ROCm", "Tuning", "Script"],
    description: "Added ROCm support to the MoE tuning script, enabling multi-GPU tuning via torchrun on AMD hardware.",
  },
  {
    id: "rocmvllm-250",
    repo: REPO.VLLM_ROCM,
    number: 250,
    url: "https://github.com/ROCm/vllm/pull/250",
    title: "fp8 moe configs. Mixtral-8x(7B,22B) TP=1,2,4,8",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-10-29",
    mergedDate: "2024-10-30",
    tags: ["FP8", "MoE", "Mixtral", "Config", "MI300"],
    description: "Added FP8 MoE tuned configs for Mixtral-8x7B and 8x22B across all TP degrees on MI300.",
  },
  {
    id: "rocmvllm-212",
    repo: REPO.VLLM_ROCM,
    number: 212,
    url: "https://github.com/ROCm/vllm/pull/212",
    title: "fix dbrx weight loader",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2024-09-26",
    mergedDate: "2024-10-01",
    tags: ["DBRX", "Weight Loading", "Bugfix"],
    description: "Fixed DBRX weight loader for compatibility with updated FusedMoe class.",
  },
  {
    id: "rocmvllm-211",
    repo: REPO.VLLM_ROCM,
    number: 211,
    url: "https://github.com/ROCm/vllm/pull/211",
    title: "extend moe padding to DUMMY weights",
    state: STATE.MERGED,
    category: CAT.MODEL,
    date: "2024-09-26",
    mergedDate: "2024-09-26",
    tags: ["MoE", "DummyLoader", "Padding"],
    description: "Extended MoE padding support to dummy weight loader for profiling without real checkpoints.",
  },
  {
    id: "rocmvllm-186",
    repo: REPO.VLLM_ROCM,
    number: 186,
    url: "https://github.com/ROCm/vllm/pull/186",
    title: "refactor dbrx experts to use FusedMoe layer",
    state: STATE.MERGED,
    category: CAT.MODEL,
    date: "2024-09-16",
    mergedDate: "2024-09-17",
    tags: ["DBRX", "MoE", "Refactor"],
    description: "Refactored DBRX expert layer to use the FusedMoe class in the ROCm fork.",
  },
  {
    id: "rocmvllm-179",
    repo: REPO.VLLM_ROCM,
    number: 179,
    url: "https://github.com/ROCm/vllm/pull/179",
    title: "Update benchmark_mixtral_moe_rocm.py",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2024-09-11",
    mergedDate: "2024-09-11",
    tags: ["Benchmarking", "Mixtral", "MoE", "Script"],
    description: "Updated Mixtral MoE benchmarking script for ROCm with improved metrics collection.",
  },
  {
    id: "rocmvllm-172",
    repo: REPO.VLLM_ROCM,
    number: 172,
    url: "https://github.com/ROCm/vllm/pull/172",
    title: "[fix] moe padding for reading correct tuned config",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2024-09-06",
    mergedDate: "2024-09-06",
    tags: ["MoE", "Padding", "Config", "Bugfix"],
    description: "Fixed MoE padding logic to correctly read tuned configs when padding is applied.",
  },
  {
    id: "rocmvllm-150",
    repo: REPO.VLLM_ROCM,
    number: 150,
    url: "https://github.com/ROCm/vllm/pull/150",
    title: "Revert re-tune moe 7B(TP=4,8) & 22B(TP=8,16) on CPX/NPS4",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-08-22",
    mergedDate: "2024-08-22",
    tags: ["MoE", "Revert", "CPX", "NPS4"],
    description: "Reverted MoE tuning update for CPX/NPS4 due to regression.",
  },
  {
    id: "rocmvllm-148",
    repo: REPO.VLLM_ROCM,
    number: 148,
    url: "https://github.com/ROCm/vllm/pull/148",
    title: "re-tune moe 7B(TP=4,8) & 22B(TP=8,16) on CPX/NPS4",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-08-22",
    mergedDate: "2024-08-22",
    tags: ["MoE", "Tuning", "CPX", "NPS4", "MI300"],
    description: "Re-tuned Mixtral-8x7B (TP=4,8) and 8x22B (TP=8,16) MoE configs on CPX/NPS4 topology.",
  },
  {
    id: "rocmvllm-131",
    repo: REPO.VLLM_ROCM,
    number: 131,
    url: "https://github.com/ROCm/vllm/pull/131",
    title: "Tuned moe 7B(TP=1) & 22B(TP=2)",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-08-13",
    mergedDate: "2024-08-13",
    tags: ["MoE", "Tuning", "Mixtral", "Config"],
    description: "Added tuned MoE configs for Mixtral-8x7B at TP=1 and Mixtral-8x22B at TP=2.",
  },
  {
    id: "rocmvllm-86",
    repo: REPO.VLLM_ROCM,
    number: 86,
    url: "https://github.com/ROCm/vllm/pull/86",
    title: "moe tuning for larger input lens",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-07-12",
    mergedDate: "2024-07-12",
    tags: ["MoE", "Tuning", "Long Context"],
    description: "Extended MoE tuning to cover larger input sequence lengths.",
  },
  {
    id: "rocmvllm-85",
    repo: REPO.VLLM_ROCM,
    number: 85,
    url: "https://github.com/ROCm/vllm/pull/85",
    title: "Mixtral-8x22B tuning mi308x",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-07-10",
    mergedDate: "2024-07-11",
    tags: ["MoE", "Mixtral", "MI308X", "Config"],
    description: "Added tuned MoE configs for Mixtral-8x22B on MI308X hardware.",
  },
  {
    id: "rocmvllm-84",
    repo: REPO.VLLM_ROCM,
    number: 84,
    url: "https://github.com/ROCm/vllm/pull/84",
    title: "TP=1 moe tuning for mixtral-8x7B",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-07-10",
    mergedDate: "2024-07-10",
    tags: ["MoE", "Mixtral", "MI300", "TP1", "Config"],
    description: "Added TP=1 tuned MoE configs for Mixtral-8x7B on MI300.",
  },
  {
    id: "rocmvllm-80",
    repo: REPO.VLLM_ROCM,
    number: 80,
    url: "https://github.com/ROCm/vllm/pull/80",
    title: "Mixtral moe tuning for mi308",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-07-08",
    mergedDate: "2024-07-08",
    tags: ["MoE", "Mixtral", "MI308", "Config"],
    description: "Added Mixtral MoE tuned configs for MI308 hardware.",
  },
  {
    id: "rocmvllm-53",
    repo: REPO.VLLM_ROCM,
    number: 53,
    url: "https://github.com/ROCm/vllm/pull/53",
    title: "Revert Revert Tune fused_moe_kernel",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-06-14",
    mergedDate: "2024-06-14",
    tags: ["MoE", "Triton", "Kernel", "Revert"],
    description: "Re-applied fused_moe_kernel tuning changes after reverting a bad revert.",
  },
  {
    id: "rocmvllm-52",
    repo: REPO.VLLM_ROCM,
    number: 52,
    url: "https://github.com/ROCm/vllm/pull/52",
    title: "fix __init__ files",
    state: STATE.MERGED,
    category: CAT.BUGFIX,
    date: "2024-06-14",
    mergedDate: "2024-06-14",
    tags: ["Bugfix", "Import"],
    description: "Fixed missing __init__ files that broke module imports in the ROCm vLLM fork.",
  },
  {
    id: "rocmvllm-33",
    repo: REPO.VLLM_ROCM,
    number: 33,
    url: "https://github.com/ROCm/vllm/pull/33",
    title: "tuned moe configs v2",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-06-03",
    mergedDate: "2024-06-03",
    tags: ["MoE", "Triton", "Config", "MI300"],
    description: "Second iteration of tuned fused_moe Triton kernel configs for MI300.",
  },
  {
    id: "rocmvllm-14",
    repo: REPO.VLLM_ROCM,
    number: 14,
    url: "https://github.com/ROCm/vllm/pull/14",
    title: "enable fused topK_softmax kernel for hip",
    state: STATE.MERGED,
    category: CAT.KERNEL,
    date: "2024-05-16",
    mergedDate: "2024-05-16",
    tags: ["Triton", "TopK", "Softmax", "HIP", "MoE"],
    description: "Enabled the fused top-K softmax kernel in the ROCm/HIP backend for MoE routing.",
    impact: "5%+ throughput improvement on MoE models",
  },
  {
    id: "rocmvllm-13",
    repo: REPO.VLLM_ROCM,
    number: 13,
    url: "https://github.com/ROCm/vllm/pull/13",
    title: "add mi300 fused_moe tuned configs",
    state: STATE.MERGED,
    category: CAT.MOE,
    date: "2024-05-09",
    mergedDate: "2024-05-09",
    tags: ["MoE", "Triton", "MI300", "Config"],
    description: "First MI300 tuned fused_moe Triton kernel configs — earliest contribution to ROCm/vllm.",
  },

  // ── ROCm/aiter ───────────────────────────────────────

  {
    id: "aiter-1147",
    repo: REPO.AITER,
    number: 1147,
    url: "https://github.com/ROCm/aiter/pull/1147",
    title: "Update vllm_benchmark.yaml",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-10-09",
    mergedDate: "2025-10-10",
    tags: ["CI", "Benchmarking", "YAML"],
    description: "Updated AITER vLLM benchmark CI configuration.",
  },
  {
    id: "aiter-1124",
    repo: REPO.AITER,
    number: 1124,
    url: "https://github.com/ROCm/aiter/pull/1124",
    title: "[aiter ci] vllm fp8 kv-cache tests | Deepseek & Mixtral",
    state: STATE.MERGED,
    category: CAT.INFRA,
    date: "2025-10-01",
    mergedDate: "2025-10-02",
    tags: ["CI", "FP8", "KV-Cache", "Deepseek", "Mixtral", "Testing"],
    description: "Added FP8 KV-cache CI tests for Deepseek and Mixtral to the AITER pipeline as part of CI overhaul.",
    impact: "Part of the 6 hrs → 12 min CI overhaul",
  },

  // ── ROCm/triton ──────────────────────────────────────

  {
    id: "triton-698",
    repo: REPO.TRITON_ROCM,
    number: 698,
    url: "https://github.com/ROCm/triton/pull/698",
    title: "Fold fp_to_fp op with zero constant input (#5007)",
    state: STATE.MERGED,
    category: CAT.KERNEL,
    date: "2025-01-11",
    mergedDate: "2025-01-11",
    tags: ["Triton", "ROCm", "Compiler", "Optimization"],
    description: "Added compiler optimization to fold fp_to_fp operations with zero constant inputs in the Triton ROCm backend.",
  },

  // ── mlc-ai/xgrammar ──────────────────────────────────

  {
    id: "xgrammar-476",
    repo: REPO.XGRAMMAR,
    number: 476,
    url: "https://github.com/mlc-ai/xgrammar/pull/476",
    title: "Fix warp_size in triton kernel for AMD GPUs",
    state: STATE.MERGED,
    category: CAT.MISC,
    date: "2025-11-20",
    mergedDate: "2025-12-18",
    tags: ["Triton", "AMD", "warp_size", "Bugfix"],
    description: "Fixed hardcoded CUDA warp size (32) in xgrammar's Triton kernel to correctly use AMD's warp size (64) on ROCm.",
  },

];


// ============================================================
// ISSUES
// ============================================================
const ISSUES = [
  {
    id: "issue-vllm-29109",
    repo: REPO.VLLM_UPSTREAM,
    number: 29109,
    url: "https://github.com/vllm-project/vllm/issues/29109",
    title: "[Bug]: Speculative decoding fails with Llama4-eagle",
    state: "closed",
    date: "2025-11-20",
    closedDate: "2026-01-06",
    tags: ["Llama4", "Eagle", "Speculative Decoding", "Bug Report"],
    description: "Reported and tracked a bug where Llama4-eagle speculative decoding fails due to missing lm_head attribute. Resolved via PR #29926.",
  },
  {
    id: "issue-vllm-19579",
    repo: REPO.VLLM_UPSTREAM,
    number: 19579,
    url: "https://github.com/vllm-project/vllm/issues/19579",
    title: "[Bug]: V1 piecewise cudagraph capture size on ROCm is much higher than on cuda",
    state: "closed",
    date: "2025-06-12",
    closedDate: "2025-10-17",
    tags: ["ROCm", "CudaGraph", "HipGraph", "vLLM-V1", "Performance", "Bug Report"],
    description: "Reported the CudaGraph capture size mismatch on ROCm in vLLM V1. Investigation led to root cause identification resolved in ROCm-7 release.",
  },
  {
    id: "issue-pytorch-2286",
    repo: REPO.PYTORCH_ROCM,
    number: 2286,
    url: "https://github.com/ROCm/pytorch/issues/2286",
    title: "Memory issues in nn.Linear due to creation of an empty tensor",
    state: "closed",
    date: "2025-06-19",
    closedDate: "2025-07-11",
    tags: ["PyTorch", "ROCm", "Memory", "nn.Linear", "Bug Report"],
    description: "Filed and tracked a memory issue in ROCm PyTorch's nn.Linear caused by unnecessary empty tensor creation affecting hipblasLT memory pool.",
  },
];


// ============================================================
// REVIEWS (on others' PRs)
// ============================================================
const REVIEWS = [
  // ── 🆕 New reviews auto-added by fetch_contributions.py — review & enrich ──
  {
    id: "review-vllm-44132",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 44132,
    url: "https://github.com/vllm-project/vllm/pull/44132#pullrequestreview-4439632060",
    title: "[Quantization] add online fp8 ptpc",
    prState: "merged",
    reviewType: "CHANGES_REQUESTED",
    date: "2026-06-05",
    tags: [],
  },
  {
    id: "review-vllm-44514",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 44514,
    url: "https://github.com/vllm-project/vllm/pull/44514#pullrequestreview-4437417377",
    title: "Deprecate old FP8 online MoE quantization class",
    prState: "merged",
    reviewType: "COMMENTED",
    date: "2026-06-05",
    tags: [],
  },
  {
    id: "review-vllm-41293",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 41293,
    url: "https://github.com/vllm-project/vllm/pull/41293#pullrequestreview-4293848566",
    title: "[Bugfix][ROCm] Fix FP8 per-tensor scale rank mismatch causing Inductor assertion failure",
    prState: "closed",
    reviewType: "COMMENTED",
    date: "2026-05-14",
    tags: [],
  },
  {
    id: "review-vllm-41197",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 41197,
    url: "https://github.com/vllm-project/vllm/pull/41197#pullrequestreview-4274687604",
    title: "[RoCm][benchmark][perf] fix moe tuning script for RDNA",
    prState: "open",
    reviewType: "COMMENTED",
    date: "2026-05-12",
    tags: [],
  },
  {
    id: "review-vllm-41634",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 41634,
    url: "https://github.com/vllm-project/vllm/pull/41634#pullrequestreview-4230121226",
    title: "[CI][ROCm] Ship RIXL with `vllm/vllm-openai-rocm`",
    prState: "merged",
    reviewType: "APPROVED",
    date: "2026-05-05",
    tags: [],
  },
  // vllm-project/vllm
  {
    id: "review-vllm-34798",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 34798,
    url: "https://github.com/vllm-project/vllm/pull/34798#pullrequestreview-3827174777",
    title: "[Mamba1] - Kernel Level Chunk Alignment for Prefix Caching",
    prState: "merged",
    reviewType: "CHANGES_REQUESTED",
    date: "2026-02-19",
    tags: ["Mamba", "Prefix Caching", "Kernel", "ROCm Compatibility"],
    description: "Reviewed ROCm compatibility of a Mamba1 prefix caching fix. Identified two unused constexpr declarations (kNThreads, kChunkSize) that are benign on CUDA but cause compilation failures on ROCm. Was independently working on a similar fix at the time. Suggested inline deletions with explanation. Followed up with companion PR #34977.",
    impact: "Ensured Mamba1 prefix caching fix compiled correctly on AMD ROCm — change required before PR could merge",
  },
  {
    id: "review-vllm-26670",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 26670,
    url: "https://github.com/vllm-project/vllm/pull/26670",
    title: "[ROCm] Add AMD GPU support on Deepseek v3.2 and SparseMLA",
    prState: "merged",
    date: "2025-10-13",
    tags: ["ROCm", "Deepseek", "SparseMLA", "AMD"],
  },
  {
    id: "review-vllm-16263",
    repo: REPO.VLLM_UPSTREAM,
    prNumber: 16263,
    url: "https://github.com/vllm-project/vllm/pull/16263",
    title: "[Hardware][AMD] Improve OAM device ID + llama4 Maverick MOE tuning",
    prState: "merged",
    date: "2025-04-08",
    tags: ["AMD", "Llama4", "MoE", "OAM", "Hardware"],
  },
  // ROCm/aiter
  {
    id: "review-aiter-2360",
    repo: REPO.AITER,
    prNumber: 2360,
    url: "https://github.com/ROCm/aiter/pull/2360",
    title: "[TRITON] Unified attention FP8 cleanup",
    prState: "open",
    date: "2026-03-19",
    tags: ["Triton", "FP8", "Attention", "Cleanup"],
  },
  // ROCm/vllm
  {
    id: "review-rocmvllm-506",
    repo: REPO.VLLM_ROCM,
    prNumber: 506,
    url: "https://github.com/ROCm/vllm/pull/506",
    title: "Fix fused moe",
    prState: "merged",
    date: "2025-04-07",
    tags: ["MoE", "Bugfix"],
  },
  {
    id: "review-rocmvllm-464",
    repo: REPO.VLLM_ROCM,
    prNumber: 464,
    url: "https://github.com/ROCm/vllm/pull/464",
    title: "Fixing the shape to use in padding calculation",
    prState: "merged",
    date: "2025-03-07",
    tags: ["MoE", "Padding", "Shape"],
  },
  {
    id: "review-rocmvllm-398",
    repo: REPO.VLLM_ROCM,
    prNumber: 398,
    url: "https://github.com/ROCm/vllm/pull/398",
    title: "Add tuned moe config for qwen1.5_moe_A2.7B",
    prState: "merged",
    date: "2025-02-03",
    tags: ["MoE", "Qwen", "Config"],
  },
  {
    id: "review-rocmvllm-224",
    repo: REPO.VLLM_ROCM,
    prNumber: 224,
    url: "https://github.com/ROCm/vllm/pull/224",
    title: "Moe align pr",
    prState: "merged",
    date: "2024-10-07",
    tags: ["MoE", "Sync"],
  },
  {
    id: "review-rocmvllm-207",
    repo: REPO.VLLM_ROCM,
    prNumber: 207,
    url: "https://github.com/ROCm/vllm/pull/207",
    title: "Revert changing fused moe kernel chunk size default to 32k",
    prState: "merged",
    date: "2024-09-25",
    tags: ["MoE", "Kernel", "Revert"],
  },
  {
    id: "review-rocmvllm-204",
    repo: REPO.VLLM_ROCM,
    prNumber: 204,
    url: "https://github.com/ROCm/vllm/pull/204",
    title: "Gating n=0 case from skinny gemm",
    prState: "merged",
    date: "2024-09-23",
    tags: ["MoE", "GEMM", "Kernel"],
  },
  {
    id: "review-rocmvllm-190",
    repo: REPO.VLLM_ROCM,
    prNumber: 190,
    url: "https://github.com/ROCm/vllm/pull/190",
    title: "Disable moe padding by default and enable fp8 padding by default",
    prState: "merged",
    date: "2024-09-17",
    tags: ["MoE", "FP8", "Padding", "Config"],
  },
];


// ============================================================
// COMMENTS (notable standalone comments on others' PRs/issues)
// These are significant technical comments that don't qualify
// as a full review but represent meaningful contributions.
// Schema: repo, prNumber/issueNumber, url (direct anchor link),
//         title (PR/issue title), date, description, tags
// ============================================================
const COMMENTS = [
  // Add entries here as you find notable comments.
  // Example template:
  // {
  //   id: "comment-vllm-XXXXX",
  //   repo: REPO.VLLM_UPSTREAM,
  //   prNumber: 12345,          // or issueNumber: 12345
  //   url: "https://github.com/vllm-project/vllm/pull/12345#issuecomment-XXXXXXX",
  //   prTitle: "PR title here",
  //   date: "2025-01-01",
  //   description: "What the comment said / contributed.",
  //   tags: ["ROCm", "Bug"],
  // },
];


// ============================================================
// INTERNAL WORK (no GitHub URL — AMD internal / client)
// ============================================================
const INTERNAL_WORK = [
  {
    id: "int-moe-tuning-system",
    year: 2024,
    month: 7,
    title: "MoE Auto-Tuning System — Multi-GPU (torchrun)",
    category: CAT.MOE,
    description: "Designed and built an end-to-end auto-tuning system for MoE Triton kernels on ROCm targeting Mixtral models. Integrated multi-GPU tuning via torchrun and extended to TP1–TP8 configurations.",
    impact: "40% gain (TP1), 25% (TP2), 18% (TP4), 12% (TP8) on MI308",
    tags: ["Triton", "ROCm", "MoE", "torchrun", "MI308"],
    clients: [],
  },
  {
    id: "int-client-alibaba",
    year: 2024,
    month: 9,
    title: "Client: Alibaba — Mixtral 1.3× Throughput Target",
    category: CAT.CLIENT,
    description: "Tuned MoE kernels and serving configuration to meet Alibaba's Mixtral throughput target.",
    impact: "1.3× throughput target met on schedule",
    tags: ["Mixtral", "MoE", "Client"],
    clients: ["Alibaba"],
  },
  {
    id: "int-client-bytedance",
    year: 2024,
    month: 9,
    title: "Client: ByteDance — 23ms Decode Latency SLA",
    category: CAT.CLIENT,
    description: "Profiled and optimized vLLM serving for ByteDance's strict 23ms per-token decode latency SLA, including server mode debugging and Qwen2-7B workload tuning.",
    impact: "23ms decode SLA achieved",
    tags: ["Latency", "Qwen2", "Serving"],
    clients: ["ByteDance"],
  },
  {
    id: "int-client-databricks",
    year: 2024,
    month: 10,
    title: "Client: Databricks — DBRX FP8 MoE Optimization",
    category: CAT.CLIENT,
    description: "Refactored DBRX model integration in the ROCm vLLM fork and added FP8 MoE tuning support for Databricks' production serving requirements.",
    impact: "DBRX FP8 MoE serving enabled",
    tags: ["DBRX", "FP8", "MoE"],
    clients: ["Databricks"],
  },
  {
    id: "int-moe-final-branch",
    year: 2024,
    month: 10,
    title: "moe_final Branch — 6 Production Releases",
    category: CAT.INFRA,
    description: "Maintained the moe_final integration branch as the stable reference for MoE work, managing cherry-picks, conflicts, and 6 tagged releases used across client deployments.",
    impact: "6 production releases shipped",
    tags: ["Branch Management", "Release", "MoE"],
    clients: [],
  },
  {
    id: "int-backend-comparison",
    year: 2024,
    month: 11,
    title: "Backend Analysis: torchrun vs MP vs Ray",
    category: CAT.ANALYSIS,
    description: "Conducted systematic performance and reliability comparison of vLLM's three multi-process backends (torchrun, multiprocessing, Ray) to guide production deployment decisions.",
    impact: "Informed backend selection for client deployments",
    tags: ["torchrun", "Ray", "Analysis", "Multi-GPU"],
    clients: [],
  },
  {
    id: "int-knowledge-sharing-2024",
    year: 2024,
    month: 11,
    title: "Knowledge Sharing — Presentations & GPU Tooling",
    category: CAT.KNOWLEDGE,
    description: "Delivered team presentations on CPX-SPX mode and dummy weight loader usage. Created benchmarking scripts and who_is_it.sh for GPU ownership tracking.",
    impact: "Improved team GPU utilization and onboarding",
    tags: ["Documentation", "Scripting", "Training"],
    clients: [],
  },
  {
    id: "int-vllm-trtllm",
    year: 2025,
    month: 2,
    title: "Deep-Dive: vLLM vs TRT-LLM — TTFT & Throughput Analysis",
    category: CAT.ANALYSIS,
    description: "Comprehensive TTFT and throughput comparison between vLLM and TensorRT-LLM using nsys profiler traces. Identified 3 actionable optimization areas. Documented in custom PPT.",
    impact: "Identified key optimization gaps vs TRT-LLM",
    tags: ["TRT-LLM", "Benchmarking", "nsys", "Prefill", "Analysis"],
    clients: [],
  },
  {
    id: "int-reshape-cache-kernel",
    year: 2025,
    month: 3,
    title: "reshape_and_update_cache_flash — Triton Kernel Analysis",
    category: CAT.KERNEL,
    description: "Developed and benchmarked a new Triton kernel for flash-attention KV cache update with rope integration. Analyzed multiple variants and documented rope/cache kernel timings.",
    impact: "Identified optimal reshape+cache variant for production",
    tags: ["Triton", "KV-Cache", "Flash Attention", "Rope"],
    clients: [],
  },
  {
    id: "int-kvcache-docs",
    year: 2025,
    month: 3,
    title: "KV-Cache Architecture Documentation",
    category: CAT.KNOWLEDGE,
    description: "Authored internal documentation covering GPU vs CPU cache, block sizing, and cache type taxonomy for vLLM's paged attention system.",
    impact: "Reference used by 4+ team members for onboarding",
    tags: ["Documentation", "KV-Cache", "paged attention"],
    clients: [],
  },
  {
    id: "int-hipgraph-investigation",
    year: 2025,
    month: 6,
    title: "vLLM-V1 CudaGraph/HipGraph Size Issue — Root Cause Investigation",
    category: CAT.ANALYSIS,
    description: "Conducted deep investigation into graph capture size mismatch in vLLM V1, analyzing pytorch hipblasLT memory pool behavior and torch.compile + cudagraph integration. Root cause resolved in ROCm-7.",
    impact: "CudaGraph size issue resolved in ROCm-7 release",
    tags: ["HipGraph", "CudaGraph", "vLLM-V1", "torch.compile", "Analysis"],
    clients: [],
  },
  {
    id: "int-client-characterai",
    year: 2025,
    month: 8,
    title: "Client: CharacterAI — Deepseek Correctness & Performance",
    category: CAT.CLIENT,
    description: "End-to-end correctness validation and performance profiling for CharacterAI's Deepseek deployment on AMD GPUs. Resolved JIT kernel dispatch disparity between vllm serve and vllm bench.",
    impact: "Unblocked CharacterAI Deepseek production deployment",
    tags: ["Deepseek", "JIT", "Profiling"],
    clients: ["CharacterAI"],
  },
  {
    id: "int-aiter-ci-overhaul",
    year: 2025,
    month: 9,
    title: "AITER CI Overhaul: Buildkite → GitHub Actions (6 hrs → 12 min)",
    category: CAT.INFRA,
    description: "Redesigned AITER CI pipeline from Buildkite to GitHub Actions with parallelized build stages, pre-built Docker caching, and incremental testing. Added Deepseek + FP8 KV cache to the test suite.",
    impact: "Build time: 6 hours → 12 minutes (30× speedup)",
    tags: ["CI", "GitHub Actions", "Buildkite", "Docker"],
    clients: [],
  },
  {
    id: "int-client-tencent",
    year: 2025,
    month: 9,
    title: "Client: Tencent — Deepseek Serving on AMD",
    category: CAT.CLIENT,
    description: "Supported Tencent's Deepseek serving deployment on AMD infrastructure, resolving configuration and performance issues.",
    impact: "Deepseek serving enabled for Tencent on AMD GPUs",
    tags: ["Deepseek", "Client"],
    clients: ["Tencent"],
  },
  {
    id: "int-w4a8-client",
    year: 2026,
    month: 3,
    title: "w4a8 Quark Quantization — gpt-oss-120b End-to-End Delivery",
    category: CAT.CLIENT,
    description: "End-to-end testing and delivery of w4a8 Quark quantization for the gpt-oss-120b model. Covered LinearLayer w4a8 and fp8×fp8 attention PRs through full validation.",
    impact: "120B model serving at w4a8 precision validated and delivered",
    tags: ["Quantization", "w4a8", "FP8", "Quark", "120B"],
    clients: [],
  },
  {
    id: "int-pd-disagg-rocm",
    year: 2026,
    month: 4,
    title: "Disaggregated Prefill-Decode — Single-Node Setup & Testing on ROCm",
    category: CAT.ANALYSIS,
    description: "Set up and tested a single-node disaggregated prefill-decode (P/D) serving configuration for vLLM on ROCm, validating the split-phase architecture end-to-end on AMD GPUs.",
    impact: "Working single-node disaggregated P/D configuration validated on ROCm",
    tags: ["Disaggregated Serving", "Prefill-Decode", "ROCm"],
    clients: [],
  },
  {
    id: "int-ci-overhaul-rocm-2026",
    year: 2026,
    month: 5,
    title: "vLLM CI Overhaul — Fixing Failing ROCm Test Groups (Ongoing)",
    category: CAT.INFRA,
    description: "Ongoing effort to investigate and fix failing vLLM CI tests on ROCm, prioritizing high-value test groups and bringing them to green on AMD hardware.",
    impact: "Multiple key CI test groups restored to green on AMD (ongoing)",
    tags: ["CI", "ROCm", "Testing"],
    clients: [],
  },
];


// ============================================================
// PR CATEGORY DISPLAY ORDER
// ============================================================
// Order the category sections appear in on the Pull Requests tab,
// leading with the most technically substantial work.
const PR_CATEGORY_SECTION_ORDER = [
  CAT.QUANT,
  CAT.KERNEL,
  CAT.MODEL,
  CAT.MOE,
  CAT.BUGFIX,
  CAT.INFRA,
  CAT.MISC,
];

// Hand-curated importance order (id list, most important first) for
// categories where a plain heuristic can't tell tuned-config grunt work
// apart from a genuinely novel contribution. Any visible PR in these
// categories not listed here falls back to the heuristic score below.
const PR_CATEGORY_MANUAL_ORDER = {
  [CAT.KERNEL]: ["vllm-4927", "vllm-23264", "triton-698"],
  [CAT.QUANT]:  ["vllm-35316", "vllm-36927", "vllm-38296"],
  [CAT.MODEL]:  ["vllm-8518", "vllm-8969"],
  [CAT.MOE]: [
    "vllm-12049", "vllm-14068", "vllm-4951",
    "vllm-12558", "vllm-16847", "vllm-13503",
    "vllm-13577", "vllm-12408", "vllm-5932",
  ],
  [CAT.BUGFIX]: [
    "vllm-16426", "vllm-29244", "vllm-29439", "vllm-37606", "vllm-29926", 
    "vllm-18445", "xgrammar-476", "vllm-13438", "vllm-45072", "vllm-32727", "vllm-32783",
    "vllm-12273",
  ],
  [CAT.INFRA]: [
    "vllm-46658",
    // systemic infra work / broad reliability or capability gains
    "aiter-1124", "vllm-11813", "vllm-8971", "vllm-32787", "vllm-42104", "vllm-45869",
    // test-suite coverage & mechanism improvements
    "vllm-32040", "vllm-29344", "vllm-34977", "vllm-44436", "aiter-1147",
    // one-off CI test fixes, newest first
    "vllm-46758", "vllm-46409", "vllm-46729", "vllm-46410",
    "vllm-45970", "vllm-45858", "vllm-45302", "vllm-43236", "vllm-31993",
    "vllm-31192", "vllm-30911", "vllm-29827", "vllm-29243", "vllm-29123",
  ],
};

const CONTRIBUTOR_RANK = {
  repo: REPO.VLLM_UPSTREAM,
  rank: 62,
  totalContributors: 2890,
  commits: 53,
  metric: "commits (all-time, default branch)",
  fetchedDate: "2026-07-08",
};


// ============================================================
// COMPUTED STATS
// ============================================================
const STATS = (() => {
  const mergedPRs    = PULL_REQUESTS.filter(p => p.state === STATE.MERGED).length;
  const upstreamPRs  = PULL_REQUESTS.filter(p => p.repo === REPO.VLLM_UPSTREAM && p.state === STATE.MERGED).length;
  const totalPRs     = PULL_REQUESTS.length;
  const clientsList  = [...new Set(INTERNAL_WORK.flatMap(w => w.clients||[]))].filter(Boolean);
  const allYears     = [...new Set([
    ...PULL_REQUESTS.map(p => new Date(p.date).getFullYear()),
    ...INTERNAL_WORK.map(w => w.year),
  ])].sort();
  const repos        = [...new Set(PULL_REQUESTS.map(p => p.repo))];

  return {
    totalPRs, mergedPRs, upstreamPRs,
    issuesCount: ISSUES.length,
    reviewsCount: REVIEWS.length,
    clientsServed: clientsList,
    years: allYears,
    repos,
  };
})();
